### ISSUE TITLE
Subtitles language

### ISSUE THREAD

**Issue by Anonymood972** [fsmdeveloper/hdo.box#2]
I just think it would be great to add french subtitles into the app... Not sure how tho I have no idea how it works, I just know opensubtitles.org has most of them

**Comment by fsmdeveloper** [comment]
Right now, I'm using Subsource.net to fetch all available subtitles for a specific movie. If you can't find French subtitles, it means they're not available on Subsource.net. I apologize.

**Comment by fsmdeveloper** [comment]
I’ll add a feature to attach local subtitles from your phone storage in the future. Thank you.
